version: "3.8"

networks:
  default:
    external: true
    name: aosom-streaming_default

services:
# -------------------------------------------------------------------------
# Telegraf - SNMP Collector Agent
# -------------------------------------------------------------------------
  telegraf-snmp-juniper:
    hostname: telegraf-snmp-juniper
    container_name: aosom-streaming_telegraf-snmp-juniper
    image: telegraf-snmp:1.20.3
    env_file: .env
    environment: 
      - TELEGRAF_SNMP_AGENTS=${TELEGRAF_SNMP_AGENTS:-"127.0.0.1:161"}
      - TELEGRAF_SNMP_VERSION=${TELEGRAF_SNMP_VERSION:-3}
      - TELEGRAF_SNMP_COMMNITY=${TELEGRAF_SNMP_COMMNITY:-public}
      - TELEGRAF_SNMP_TOKEN=${TELEGRAF_SNMP_TOKEN:-Juniper123}
      - TELEGRAF_SNMP_SEC_NAME=${TELEGRAF_SNMP_SEC_NAME:-user1snmpv3}
      - TELEGRAF_SNMP_SEC_LEVEL=${TELEGRAF_SNMP_SEC_LEVEL:-authPriv}
      - TELEGRAF_SNMP_PRIV_PROTOCOL=${TELEGRAF_SNMP_PRIV_PROTOCOL:-AES}
      - TELEGRAF_SNMP_AUTH_PROTOCOL=${TELEGRAF_SNMP_AUTH_PROTOCOL:-MD5}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-adminadmin}
      - INFLUXDB_DATABASE=${INFLUXDB_DATABASE:-telemetry}
      - INFLUXDB_RETENTION_POLICY=${INFLUXDB_RETENTION_POLICY:-autogen}
    command: sh -c "
      cat /etc/telegraf/telegraf-snmp-MAIN.conf 
          /etc/telegraf/telegraf-snmp-OUTPUT-influxdb.conf 
          /etc/telegraf/telegraf-snmp-INPUT-SNMP_IF-MIB.conf 
          /etc/telegraf/telegraf-snmp-INPUT-SNMP_BGP4-MIB.conf > /tmp/telegraf.conf &&
      sed -e 's|\"AGENTS\"|'"\$${TELEGRAF_SNMP_AGENTS}"'|' -i /tmp/telegraf.conf &&
      env && cat /tmp/telegraf.conf &&
      telegraf -debug --config /tmp/telegraf.conf"
    pull_policy: never
    restart: unless-stopped
    volumes:
      - ./config/telegraf/:/etc/telegraf/
      - /etc/localtime:/etc/localtime